INSERT INTO CONTACT (FIRST_NAME,LAST_NAME) VALUES ('Jean-Claude','Goldman');
INSERT INTO CONTACT (FIRST_NAME,LAST_NAME) VALUES ('John','Volt');
INSERT INTO CONTACT (FIRST_NAME,LAST_NAME) VALUES ('Kevina','Blum');